### ISSUE TITLE
Remove typescript-boilerplate

### ISSUE THREAD

**Issue by nokome** [stencila/dev-config#235]
I suggest deprecating / removing https://github.com/stencila/dev-config/tree/master/packages/typescript-boilerplate. I haven't used it for well over a year, I doubt anyone else is and it just add's noises to releases. All the other packages in this repo are `*-config` packages, `typescript-boilerplate` feels out of place and unnecessary.

**Comment by alex-ketch** [comment]
Agreed, will remove it soon.
