### ISSUE TITLE
feat(Semantic release): Upgrade to v16?

### ISSUE THREAD

**Issue by nokome** [stencila/dev-config#27]
Version 16 of Semantic release introduces some useful branch workflow options: https://semantic-release.gitbook.io/semantic-release/v/beta/usage/workflow-configuration.

**Comment by nokome** [comment]
OTH, may be a bit premature. Used it in Executa and it although [it said](https://travis-ci.org/stencila/executa/jobs/622535912#L1364):

```
Published release 1.0.0 on next channel
```

it actually, published to npm `latest` :scream_cat:

**Comment by alex-ketch** [comment]
hmmm... I _think_ that happened because we don't have the channels/pre-release branches configured, and the PR landed on `master`. Could be worthwhile waiting for a first round of bug-fixes anyway though

**Comment by nokome** [comment]
I configured the `branches` option and was using the `next` branch in Executa. Maybe the `@semantic-release/npm` plugin also needs to be upgraded to `beta`? Anyway, not a priority right now.

**Comment by alex-ketch** [comment]
Closed by https://github.com/stencila/dev-config/commit/6b3c958e50c7e7baa96248073051ead03eb806df
